# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '__first__'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(default='undecided', max_length=255)),
                ('order', models.IntegerField(default='100')),
                ('act_intro', models.TextField(blank=True)),
                ('stage_prep', models.TextField(blank=True)),
                ('music_sent', models.BooleanField(default=False)),
                ('act_notes', models.TextField(blank=True)),
                ('lighting_notes', models.TextField(blank=True)),
                ('start_onstage', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('introducer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='introducer', to=settings.AUTH_USER_MODEL)),
                ('kitten_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitten_id', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sm_act',
                'ordering': ['show_name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=120)),
                ('show_date', models.DateField()),
                ('show_end_date', models.DateField(null=True)),
                ('show_start', models.TimeField()),
                ('show_end_time', models.TimeField()),
                ('show_doors', models.TimeField(null=True)),
                ('show_recurring', recurrence.fields.RecurrenceField(null=True)),
                ('show_notes', models.TextField(blank=True, db_column='Notes')),
                ('show_ticket_link', models.CharField(blank=True, max_length=250, null=True)),
                ('show_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('venue_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'db_table': 'sm_show',
                'ordering': ['show_date'],
            },
        ),
        migrations.AddField(
            model_name='act',
            name='show_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showmanager.show'),
        ),
    ]
