# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 01:24
from __future__ import unicode_literals

import aldryn_categories.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('location', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_workshop', models.BooleanField(default=False)),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=1)),
                ('custom_start_date', models.DateField(blank=True, null=True)),
                ('custom_end_date', models.DateField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('spaces', models.IntegerField(default=15)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dropins', models.BooleanField(default=True)),
                ('dropin_price', models.IntegerField(default=20)),
                ('ticket_link', models.CharField(blank=True, max_length=250)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('category', aldryn_categories.fields.CategoryManyToManyField(to='aldryn_categories.Category')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Session'),
        ),
    ]
